import { Injectable, signal } from '@angular/core';
const DICT:any={
en:{home:'Home',findHome:'Find a home',signIn:'Sign in',createAccount:'Create account',download:'Download app',dashboard:'Dashboard',search:'Search',favourites:'Favourites',casaMatch:'CasaMatch AI',messages:'Messages',wallet:'Wallet',profile:'Profile',settings:'Settings',notifications:'Notifications',reports:'Reports',listings:'Listings',addProperty:'Add property',logout:'Log out',hero:'A smarter way to find a place you can truly call home.',heroSub:'Discover verified homes, connect safely with property owners and let CasaMatch AI help you find the right fit across Cameroon.',explore:'Explore homes',ownerCta:'List your property',safe:'Safer conversations',verified:'Verified listings',smart:'AI-powered matching',mobileOnly:'Continue on the SweetCasa app',mobileOnlySub:'This feature is designed for the full SweetCasa experience. Download the app to continue.',android:'Get it for Android',ios:'Get it for iPhone'},
fr:{home:'Accueil',findHome:'Trouver un logement',signIn:'Connexion',createAccount:'Créer un compte',download:"Télécharger l’app",dashboard:'Tableau de bord',search:'Recherche',favourites:'Favoris',casaMatch:'CasaMatch IA',messages:'Messages',wallet:'Portefeuille',profile:'Profil',settings:'Paramètres',notifications:'Notifications',reports:'Signalements',listings:'Annonces',addProperty:'Ajouter un bien',logout:'Déconnexion',hero:'Une façon plus intelligente de trouver un logement où vous vous sentirez vraiment chez vous.',heroSub:'Découvrez des logements vérifiés, échangez en toute sécurité avec les propriétaires et laissez CasaMatch IA vous aider à trouver le bon choix au Cameroun.',explore:'Explorer les logements',ownerCta:'Publier un bien',safe:'Échanges plus sûrs',verified:'Annonces vérifiées',smart:'Recherche assistée par IA',mobileOnly:"Continuez dans l’application SweetCasa",mobileOnlySub:"Cette fonctionnalité est conçue pour l’expérience SweetCasa complète. Téléchargez l’application pour continuer.",android:'Obtenir sur Android',ios:'Obtenir sur iPhone'}
};
@Injectable({providedIn:'root'}) export class I18nService{
 lang=signal<'en'|'fr'>((localStorage.getItem('sc-lang') as any)||'en');
 t(key:string){return DICT[this.lang()]?.[key]||DICT.en[key]||key;}
 setLang(v:'en'|'fr'){this.lang.set(v);localStorage.setItem('sc-lang',v);document.documentElement.lang=v;}
}