import { Component, OnInit, OnDestroy, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { I18nService } from '../../core/services/i18n.service';

@Component({selector:'sc-listings',imports:[DecimalPipe,RouterLink,FormsModule],templateUrl:'./listings.html',styleUrl:'./listings.css'})
export class Listings implements OnInit, OnDestroy{
 items=signal<any[]>([]);loading=signal(true);error=signal('');editOpen=signal(false);saving=signal(false);editError=signal('');editSuccess=signal('');editing:any=null;
 private statusTimer:any=null;
 form:any={}; newPhotos:File[]=[]; newFloorPlan:File|null=null; newLegalDocuments:File[]=[]; readonly amenities=['Wifi','Electricity','Water Supply','Gated','Parking','Green Area','Generator','School','Bank','Restaurant','Market','Clinic']; readonly types=['Room / Studio','Apartment','Bungalow (Maison Basse)','Office','Duplex / Villa','Guest House / Hotel','Penthouse','Mansion / Residence','Commercial Building (Immeuble)','School Dorm']; readonly frequencies=['Daily','Weekly','Monthly','Quarterly','Yearly','For Sale'];
 constructor(private api:ApiService,private router:Router,private route:ActivatedRoute,public i18n:I18nService){}
 ngOnInit(){this.load();this.statusTimer=setInterval(()=>this.refreshStatuses(),3000)}
 ngOnDestroy(){if(this.statusTimer)clearInterval(this.statusTimer)}
 load(){this.loading.set(true);this.api.get<any>('/listings/mine').subscribe({next:r=>{const rows=r.listings||[];this.items.set(rows);this.loading.set(false);const editId=Number(this.route.snapshot.queryParamMap.get('edit'));if(editId){const item=rows.find((x:any)=>Number(x.id)===editId);if(item)this.edit(item)}},error:e=>{this.error.set(e.error?.error||'Could not load your listings.');this.loading.set(false)}})}
 refreshStatuses(){this.api.get<any>('/listings/mine',{_statusCheck:Date.now()}).subscribe({next:r=>{const fresh=r.listings||[];this.items.update(current=>current.map(old=>{const n=fresh.find((x:any)=>Number(x.id)===Number(old.id));return n?{...old,...n}:old}))},error:()=>{}})}
 openListing(l:any){if(String(l.status)!=='Approved'){this.edit(l);return}this.router.navigate(['/owner/property',l.id])}
 remove(id:any,e?:Event){e?.stopPropagation();if(!confirm(this.i18n.text('Delete this listing?')))return;this.api.delete(`/listings/${id}`).subscribe({next:()=>this.items.update(v=>v.filter(x=>x.id!==id))})}
 image(l:any){return l.images?.[0]?.imageUrl||l.images?.[0]?.url||'/assets/owner_list.png'}
 edit(l:any,e?:Event){e?.stopPropagation();this.editing=l;this.editError.set('');this.editSuccess.set('');this.form={title:l.title||'',type:l.type||'Apartment',country:l.country||'Cameroon',region:l.region||'',city:l.city||'',neighborhood:l.neighborhood||'',price:String(l.price??''),paymentFrequency:l.paymentFrequency||'Monthly',cautionFee:String(l.cautionFee??''),bedrooms:Number(l.bedrooms||0),bathrooms:Number(l.bathrooms||0),toilets:Number(l.toilets||0),parlors:Number(l.parlors||0),kitchens:Number(l.kitchens||0),areaSqm:String(l.areaSqm??''),description:l.description||'',visitHours:l.visitHours||'',facilities:this.parseFacilities(l.facilities??l.amenities)};this.newPhotos=[];this.newFloorPlan=null;this.newLegalDocuments=[];this.editOpen.set(true)}
 closeEdit(){if(this.saving())return;this.editOpen.set(false);this.editing=null;this.router.navigate([], {relativeTo:this.route,queryParams:{edit:null},queryParamsHandling:'merge',replaceUrl:true})}
 save(){if(!this.editing||this.saving())return;this.editError.set('');if(!String(this.form.title).trim()||!String(this.form.region).trim()||!String(this.form.city).trim()||!String(this.form.price).trim()||!String(this.form.description).trim()){this.editError.set('Please complete the required fields.');return}const fd=new FormData();const data={...this.form,price:String(this.form.price).replace(/,/g,''),cautionFee:this.form.paymentFrequency==='For Sale'?'0':String(this.form.cautionFee||'0').replace(/,/g,''),facilities:JSON.stringify(this.form.facilities||[])};Object.entries(data).forEach(([k,v])=>{if(v!==null&&v!==undefined)fd.append(k,String(v))});this.newPhotos.forEach(f=>fd.append('photos',f,f.name));if(this.newFloorPlan)fd.append('floorPlan',this.newFloorPlan,this.newFloorPlan.name);this.newLegalDocuments.forEach(f=>fd.append('legalDocuments',f,f.name));this.saving.set(true);this.api.patch<any>(`/listings/${this.editing.id}`,fd).subscribe({next:r=>{const updated=r.listing||{...this.editing,...data,status:'Pending'};this.items.update(rows=>rows.map(x=>x.id===this.editing.id?{...x,...updated,status:updated.status||'Pending'}:x));this.saving.set(false);this.editSuccess.set('Listing updated successfully. It has been sent for re-review and its status is now Pending.');setTimeout(()=>this.closeEdit(),1100)},error:e=>{this.saving.set(false);this.editError.set(e.error?.error||'Could not update this listing.')}})}
 parseFacilities(v:any){if(Array.isArray(v))return v.map((x:any)=>typeof x==='string'?x:(x.name||x.value)).filter(Boolean);try{return JSON.parse(v||'[]')}catch{return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}}
 toggleFacility(v:string){this.form.facilities=this.form.facilities.includes(v)?this.form.facilities.filter((x:string)=>x!==v):[...this.form.facilities,v]}
 pickFiles(e:Event,kind:'photos'|'floor'|'legal'){const f=Array.from((e.target as HTMLInputElement).files||[]);if(kind==='photos')this.newPhotos=f;if(kind==='floor')this.newFloorPlan=f[0]||null;if(kind==='legal')this.newLegalDocuments=f}
 statusClass(l:any){return String(l.status||'').toLowerCase()}
}
